micronaut:
  application:
    name: mn-jasper-example
#datasources:
#  default:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    dialect: POSTGRES
#    auto-commit: false